//! Generated by `wylde-panel-aggregator`.
//!
//! Do not edit by hand — your changes will be overwritten the next
//! time the aggregator runs against the repo.
//!
//! Sources read for this generation:
//!   - Core/GUI/Frontend/Panels/Chat/manifest.json
//!   - Core/GUI/Frontend/Panels/Dashboard/manifest.json
//!   - Core/GUI/Frontend/Panels/Devices/manifest.json
//!   - Core/GUI/Frontend/Panels/Memory/manifest.json
//!   - Core/GUI/Frontend/Panels/Models/manifest.json
//!   - Core/GUI/Frontend/Panels/RemoteAccess/manifest.json
//!   - Core/GUI/Frontend/Panels/Settings/manifest.json
//!   - Core/GUI/Frontend/Panels/Tools/manifest.json
//!   - Core/GUI/Frontend/Panels/Workspaces/manifest.json
//!
//! Build-time aggregator design lives in the
//! `wylde_panel_aggregator` binary; see its CLI usage there.

use crate::factories::FactoryMap;
use crate::manifest::{PanelEntry, PanelOrigin, PanelSource};
use crate::registry::{PanelRegistry, RegistryError, RegistryRow};

/// Populate the supplied registry with every compiled-in first-party
/// panel.  `factories` carries the wiring from factory strings to real
/// closures; each panel takes its closure out of the map as it is
/// registered.
///
/// Returns an error if a factory referenced in the generated source
/// isn't present in the map (caught at startup so it's a loud failure,
/// not a silent missing-tab at runtime).
pub fn register_all(
    registry: &mut PanelRegistry,
    factories: &mut FactoryMap,
) -> Result<(), RegistryError> {
    // ── core / chat  (from Core/GUI/Frontend/Panels/Chat/manifest.json) ──
    {
        let factory_key = "wylde_panel_chat::ChatPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "chat".into(),
                title: "Chat".into(),
                icon: Some("chat".into()),
                order: 5,
                version: "0.1.0".into(),
                required_services: vec![
                    "wylde-harness".into(),
                    "wylde-ollama".into(),
                    "wylde-workspaces".into(),
                ],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / dashboard  (from Core/GUI/Frontend/Panels/Dashboard/manifest.json) ──
    {
        let factory_key = "wylde_panel_dashboard::DashboardPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "dashboard".into(),
                title: "Dashboard".into(),
                icon: Some("gauge".into()),
                order: 8,
                version: "0.1.0".into(),
                required_services: vec![],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / devices  (from Core/GUI/Frontend/Panels/Devices/manifest.json) ──
    {
        let factory_key = "wylde_panel_devices::DevicesPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "devices".into(),
                title: "Devices".into(),
                icon: Some("smartphone".into()),
                order: 60,
                version: "0.1.0".into(),
                required_services: vec!["wylde-device-gate".into()],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / memory  (from Core/GUI/Frontend/Panels/Memory/manifest.json) ──
    {
        let factory_key = "wylde_panel_memory::MemoryPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "memory".into(),
                title: "Memory".into(),
                icon: Some("brain".into()),
                order: 20,
                version: "0.1.0".into(),
                required_services: vec!["wylde-harness".into(), "wylde-workspaces".into()],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / models  (from Core/GUI/Frontend/Panels/Models/manifest.json) ──
    {
        let factory_key = "wylde_panel_models::ModelsPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "models".into(),
                title: "Models".into(),
                icon: Some("cpu".into()),
                order: 40,
                version: "0.1.0".into(),
                required_services: vec![
                    "wylde-ollama".into(),
                    "wylde-vram-broker".into(),
                    "wylde-harness".into(),
                ],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / remote_access  (from Core/GUI/Frontend/Panels/RemoteAccess/manifest.json) ──
    {
        let factory_key = "wylde_panel_remote_access::RemoteAccessPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "remote_access".into(),
                title: "Remote Access".into(),
                icon: Some("globe".into()),
                order: 65,
                version: "0.1.0".into(),
                required_services: vec!["wylde-vpn".into()],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / settings  (from Core/GUI/Frontend/Panels/Settings/manifest.json) ──
    {
        let factory_key = "wylde_panel_settings::SettingsPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "settings".into(),
                title: "Settings".into(),
                icon: Some("settings".into()),
                order: 95,
                version: "0.1.0".into(),
                required_services: vec![
                    "wylde-harness".into(),
                    "wylde-ollama".into(),
                    "wylde-voice".into(),
                ],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / tools  (from Core/GUI/Frontend/Panels/Tools/manifest.json) ──
    {
        let factory_key = "wylde_panel_tools::ToolsPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "tools".into(),
                title: "Tools".into(),
                icon: Some("wrench".into()),
                order: 50,
                version: "0.1.0".into(),
                required_services: vec!["wylde-extension-bridge".into()],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }

    // ── core / workspaces  (from Core/GUI/Frontend/Panels/Workspaces/manifest.json) ──
    {
        let factory_key = "wylde_panel_workspaces::WorkspacesPanel::view";
        let factory = factories
            .take(factory_key)
            .ok_or_else(|| RegistryError::MissingFactory(factory_key.into()))?;
        registry.register_internal(RegistryRow {
            origin: PanelOrigin::FirstParty {
                service: "core".into(),
            },
            entry: PanelEntry {
                id: "workspaces".into(),
                title: "Workspaces".into(),
                icon: Some("folder".into()),
                order: 30,
                version: "0.1.0".into(),
                required_services: vec!["wylde-workspaces".into()],
                source: PanelSource::GpuiView {
                    factory: factory_key.into(),
                },
            },
            factory: Some(factory),
        })?;
    }
    Ok(())
}
