//! Cross-language wire-fixture parity test.
//!
//! Reads `tests/fixtures/wire_corpus.json` (generated by the sibling
//! Python script) and decodes each `msgpack_b64` blob through `rmp-serde`.
//! The decoded value must equal the `payload` JSON the Python side stamped
//! into the file. If this test ever fails, the two halves of the system
//! have drifted apart and the live Python services will reject the Rust
//! wire output (or vice versa).

use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Deserialize, Debug)]
struct Case {
    name: String,
    payload: serde_json::Value,
    msgpack_b64: String,
}

#[test]
fn rust_can_decode_python_msgpack_bytes() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("wire_corpus.json");
    let raw =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let corpus: Corpus = serde_json::from_str(&raw).expect("wire_corpus.json malformed");
    assert!(!corpus.cases.is_empty(), "corpus has no cases");

    for case in &corpus.cases {
        let bytes = B64
            .decode(&case.msgpack_b64)
            .unwrap_or_else(|e| panic!("[{}] b64 decode: {e}", case.name));
        let decoded: serde_json::Value = rmp_serde::from_slice(&bytes)
            .unwrap_or_else(|e| panic!("[{}] rmp-serde decode: {e}", case.name));
        assert_eq!(
            decoded, case.payload,
            "[{}] msgpack→json mismatch with Python source",
            case.name
        );
    }
}

#[test]
fn rust_msgpack_roundtrip_matches_python_for_simple_maps() {
    // For the cases whose payloads are flat string-keyed maps with no
    // ordering ambiguity, the Rust-emitted bytes should be structurally
    // identical when decoded back through Python's reference shape (which
    // we proxy here by decoding our own bytes and comparing to the JSON).
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("wire_corpus.json");
    let raw = std::fs::read_to_string(&path).expect("read corpus");
    let corpus: Corpus = serde_json::from_str(&raw).expect("parse corpus");

    for case in &corpus.cases {
        let rust_bytes = rmp_serde::to_vec_named(&case.payload)
            .unwrap_or_else(|e| panic!("[{}] rmp encode: {e}", case.name));
        let roundtrip: serde_json::Value = rmp_serde::from_slice(&rust_bytes)
            .unwrap_or_else(|e| panic!("[{}] roundtrip decode: {e}", case.name));
        assert_eq!(
            roundtrip, case.payload,
            "[{}] rmp-serde roundtrip lost data",
            case.name
        );
    }
}
