#Requires -Version 5.1
<#
.SYNOPSIS
  Download and install Wylde's vendored Neo4j + JDK runtime.

.DESCRIPTION
  The repo does not ship the Neo4j server or its JDK (~280 MB, above GitHub's
  100 MB per-file limit). This downloads pinned, checksum-verified versions
  into the layout the launcher (Core/Memgraph/run.py) expects:

      Core/Memgraph/vendor/jdk/    <- Temurin JDK 21.0.10+7    (JAVA_HOME)
      Core/Memgraph/vendor/neo4j/  <- Neo4j Community 2026.03.1

  The Neo4j distribution bundles Graph Data Science, GenAI and APOC under
  products/ and labs/; GDS 2026.03.0 is pinned + checksum-verified and
  downloaded from its GitHub release only if not already bundled.

  After extracting Neo4j the stock neo4j.conf is replaced with Wylde's tuned
  config (auth off, local Bolt on 127.0.0.1:7687, data under the user
  profile) -- vendor/ is gitignored, so that conf must be regenerated here.

  Idempotent: exits early when everything is in place, and reuses a cached,
  checksum-valid download instead of re-fetching. Bundles its own JDK, so an
  existing system Java install is never touched. Run from any directory.
#>
[CmdletBinding()]
param(
    [switch]$Force  # re-download / re-extract even if already installed
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# -- pinned versions + SHA256 checksums (verified against upstream 2026-05-31) --
$JdkVersion   = '21.0.10+7'
$Neo4jVersion = '2026.03.1'
$GdsVersion   = '2026.03.0'

$JdkUrl   = 'https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.10%2B7/OpenJDK21U-jdk_x64_windows_hotspot_21.0.10_7.zip'
$JdkSha   = '08cae782814f027f8b159d6b68823f0f87422eb475c1a0ea1abc7a4357aaf11f'
$Neo4jUrl = "https://dist.neo4j.org/neo4j-community-$Neo4jVersion-windows.zip"
$Neo4jSha = 'b99fbc92c10dc8fe98079fdb6100161ad0a8047c061d48984022d36085341968'
$GdsUrl   = "https://github.com/neo4j/graph-data-science/releases/download/$GdsVersion/neo4j-graph-data-science-$GdsVersion.jar"
$GdsSha   = 'b3ba82796e538b04b31faeb314fd42ca4c77261dc4abaaa2852d551f642b7cff'

# -- paths (relative to this script, so cwd doesn't matter) --
$RepoRoot  = Split-Path -Parent $PSScriptRoot
$VendorDir = Join-Path $RepoRoot 'Core\Memgraph\vendor'
$JdkDir    = Join-Path $VendorDir 'jdk'
$Neo4jDir  = Join-Path $VendorDir 'neo4j'
$CacheDir  = Join-Path $VendorDir '.download-cache'
$GdsTarget = Join-Path $Neo4jDir "products\neo4j-graph-data-science-$GdsVersion.jar"
$ConfFile  = Join-Path $Neo4jDir 'conf\neo4j.conf'

# -- colored logging --
function Step($m) { Write-Host "`n==> $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "  [ok] $m"  -ForegroundColor Green }
function Warn($m) { Write-Host "  [..] $m"  -ForegroundColor Yellow }
function Die($m)  { Write-Host "  [!!] $m"  -ForegroundColor Red; exit 1 }

# -- helpers --
function Test-Sha256($Path, $Expected) {
    if (-not (Test-Path $Path)) { return $false }
    return ((Get-FileHash -Algorithm SHA256 -Path $Path).Hash -ieq $Expected)
}

function Get-Verified($Url, $Sha, $OutFile) {
    $name = Split-Path $OutFile -Leaf
    if (Test-Sha256 $OutFile $Sha) { Ok "cached & verified: $name"; return }
    Warn "downloading $name ..."
    Invoke-WebRequest -Uri $Url -OutFile $OutFile -UseBasicParsing
    if (-not (Test-Sha256 $OutFile $Sha)) {
        $got = (Get-FileHash -Algorithm SHA256 -Path $OutFile).Hash
        Die "checksum mismatch for $Url`n        expected $Sha`n        got      $got"
    }
    Ok "downloaded & verified: $name"
}

function Expand-Flat($Zip, $DestDir) {
    # The upstream zips contain a single top-level folder; extract to a temp
    # dir then promote that folder so DestDir holds the contents directly.
    $tmp = Join-Path $CacheDir ('x_' + [IO.Path]::GetFileNameWithoutExtension($Zip))
    if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }
    Expand-Archive -Path $Zip -DestinationPath $tmp -Force
    $inner = Get-ChildItem $tmp -Directory | Select-Object -First 1
    if (-not $inner) { Die "archive $Zip had no top-level directory" }
    if (Test-Path $DestDir) { Remove-Item $DestDir -Recurse -Force }
    Move-Item -Path $inner.FullName -Destination $DestDir
    Remove-Item $tmp -Recurse -Force
}

function Write-Neo4jConf {
    # Stock neo4j.conf ships with auth ENABLED and HTTP on; Wylde needs
    # local-only Bolt with auth off and data stored under the user profile.
    # This is the exact runtime config the launcher expects.
    $conf = @'
# -- Wylde-tuned Neo4j configuration (regenerated by tools/install-neo4j.ps1) --
db.query.default_language=CYPHER_25
server.directories.import=import
server.windows_service_name=neo4j
dbms.security.auth_enabled=false
dbms.usage_report.enabled=false
server.default_listen_address=127.0.0.1
server.bolt.enabled=true
server.bolt.tls_level=DISABLED
server.bolt.listen_address=127.0.0.1:7687
server.bolt.advertised_address=127.0.0.1:7687
server.http.enabled=false
server.memory.heap.initial_size=512m
server.memory.heap.max_size=1g
server.memory.pagecache.size=512m
server.directories.data=%USERPROFILE%/Documents/default/core/wylde-memgraph/data
server.directories.logs=%USERPROFILE%/Documents/default/core/wylde-memgraph/logs
server.directories.transaction.logs.root=%USERPROFILE%/Documents/default/core/wylde-memgraph/data/transactions
server.jvm.additional=-XX:+UseG1GC
server.jvm.additional=-XX:-OmitStackTraceInFastThrow
server.jvm.additional=-XX:+AlwaysPreTouch
server.jvm.additional=-XX:+UnlockExperimentalVMOptions
server.jvm.additional=-XX:+TrustFinalNonStaticFields
server.jvm.additional=-XX:+DisableExplicitGC
server.jvm.additional=-Djdk.nio.maxCachedBufferSize=1024
server.jvm.additional=-Dio.netty.tryReflectionSetAccessible=true
server.jvm.additional=-Dio.netty.leakDetection.level=DISABLED
server.jvm.additional=-Djdk.tls.ephemeralDHKeySize=2048
server.jvm.additional=-Djdk.tls.rejectClientInitiatedRenegotiation=true
server.jvm.additional=-XX:FlightRecorderOptions=stackdepth=256
server.jvm.additional=-XX:+UnlockDiagnosticVMOptions
server.jvm.additional=-XX:+DebugNonSafepoints
server.jvm.additional=--add-opens=java.base/java.nio=ALL-UNNAMED
server.jvm.additional=--add-opens=java.base/java.io=ALL-UNNAMED
server.jvm.additional=--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
server.jvm.additional=--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
server.jvm.additional=--enable-native-access=ALL-UNNAMED
server.jvm.additional=-Dorg.neo4j.shaded.lucene9.vectorization.upperJavaFeatureVersion=25
server.jvm.additional=-Dlog4j2.disable.jmx=true
server.jvm.additional=-Dlog4j.layout.jsonTemplate.maxStringLength=32768
'@
    Set-Content -Path $ConfFile -Value $conf -Encoding ASCII
    Ok 'wrote Wylde neo4j.conf (auth off, bolt 127.0.0.1:7687)'
}

# -- idempotent early-exit --
$releaseFile = Join-Path $JdkDir 'release'
$jdkOk   = (Test-Path $releaseFile) -and `
           ((Get-Content $releaseFile -ErrorAction SilentlyContinue) -match [regex]::Escape($JdkVersion))
$neo4jOk = Test-Path (Join-Path $Neo4jDir 'bin\neo4j.bat')
$gdsOk   = Test-Path $GdsTarget

if ($jdkOk -and $neo4jOk -and $gdsOk -and -not $Force) {
    Step 'Wylde runtime already installed'
    Ok "JDK    $JdkVersion  -> $JdkDir"
    Ok "Neo4j  $Neo4jVersion -> $Neo4jDir"
    Ok "GDS    $GdsVersion  -> $GdsTarget"
    Write-Host "`nNothing to do. Re-run with -Force to reinstall." -ForegroundColor Green
    exit 0
}

New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null

# -- JDK --
Step "Temurin JDK $JdkVersion"
if ($jdkOk -and -not $Force) {
    Ok 'already present, skipping'
} else {
    $zip = Join-Path $CacheDir 'temurin-jdk.zip'
    Get-Verified $JdkUrl $JdkSha $zip
    Warn 'extracting JDK ...'
    Expand-Flat $zip $JdkDir
    if (-not (Test-Path (Join-Path $JdkDir 'bin\java.exe'))) { Die 'JDK extraction failed (no bin\java.exe)' }
    Ok "installed -> $JdkDir"
}

# -- Neo4j --
Step "Neo4j Community $Neo4jVersion"
if ($neo4jOk -and -not $Force) {
    Ok 'already present, skipping'
} else {
    $zip = Join-Path $CacheDir 'neo4j-community.zip'
    Get-Verified $Neo4jUrl $Neo4jSha $zip
    Warn 'extracting Neo4j ...'
    Expand-Flat $zip $Neo4jDir
    if (-not (Test-Path (Join-Path $Neo4jDir 'bin\neo4j.bat'))) { Die 'Neo4j extraction failed (no bin\neo4j.bat)' }
    Write-Neo4jConf
    Ok "installed -> $Neo4jDir"
}

# -- Graph Data Science plugin --
Step "Graph Data Science $GdsVersion"
if (Test-Path $GdsTarget) {
    Ok "present (bundled by the Neo4j distribution) -> products\$(Split-Path $GdsTarget -Leaf)"
} else {
    Warn 'not bundled by the distribution; fetching from GitHub release ...'
    New-Item -ItemType Directory -Force -Path (Split-Path $GdsTarget) | Out-Null
    Get-Verified $GdsUrl $GdsSha $GdsTarget
    Ok "installed -> $GdsTarget"
}

Step 'Done'
Ok "JDK    $JdkVersion"
Ok "Neo4j  $Neo4jVersion"
Ok "GDS    $GdsVersion"
Write-Host "`nVendored runtime ready. Next: build & launch - see docs/setup.md" -ForegroundColor Green
